# CLIMBER-X

## Components
### Climate components

* 2.5-D semi-empirical statistical–dynamical atmosphere model (SESAM)
* 3-D frictional–geostrophic ocean model (GOLDSTEIN)
* Dynamic–thermodynamic sea ice model (SISIM)
* Land surface model (PALADYN)

### Optional components
* Ocean biogeochemistry and marinesediment model (HAMOCC)
* Ice sheet model for land (SCIPOLIS and YELMO)
* Viscoelastic mantle model (VILMA)

## Model structure
* The climate components are coupled through fluxes of energy and water, which are conserved
* Momentum is not conserved, but surface wind stress is computed in the atmosphere and passed to the ocean component
* Atmosphere, ocean, sea ice and land all have a horizontal resolution of 5 x 5 degrees
* Grid cells have land–sea fractions
* Base time step: 1 day (same as coupling frequency)
* The model does not represent interannual internal climate variability such as ENSO
* The land–ocean distribution, topography and land cover can evolve with time. A
* FORTRAN 90+
* Parallelized using OpenMP
* One namelist file for each model component

## Atmosphere model: SESAM

* The spatial resolution of SESAM is 2.5-D. This means that although prognostic variables (temperature, specific humidity, dust and eddy kinetic energy) as well as many diagnostic characteristics (cloudiness, condensation, shortwave radiation, etc.) are 2-D (latitude and longitude), the calculation of horizontal energy and water transport and the vertical fluxes of longwave radiation make use of information about the 3-D distribution of temperature, humidity, and wind velocity. All the vertical variations are purely diagnostic in the model.
* At the surface, each model grid cell is divided into different macro surface types, namely ocean, sea ice, land, lakes, and ice sheets. 
* The macro surface types share the same atmospheric column but differ in surface elevation, albedo, and surface temperature and humidity. 
* Sensible heat flux, evaporation, and shortwave and longwave radiation fluxes are computed separately for each macro surface type.
* The 3-D atmospheric structure is derived using assumptions about the universal vertical structure of temperature and relative humidity in the atmosphere. 
* The temperature profile through the troposphere is a quadratic function of height, except in a 1500 m layer close to the surface where the lapse rate is a function of the near-surface atmospheric stability
* Inversion strength is determined by the surface radiative balance and the difference between near-surface air temperature and skin temperature. 
* Temperature is vertically uniform in the stratosphere. 
* The tropopause height is derived assuming that the stratosphere is in radiative equilibrium. 
* Relative humidity is taken to be constant within the planetary boundary layer, to decay exponentially in the low troposphere and to remain constant throughout the rest of the troposphere. 
* Stratospheric relative humidity is prescribed at a uniform constant value.
* The horizontal wind velocity is divided into geostrophic and ageostrophic components. 
* The geostrophic components of velocity at sea level are computed from sea-level pressure (SLP) and at any height through the troposphere by using the thermal wind approximation
* The components of the surface wind are computed using the Taylor model

* The ageostrophic wind components in the planetary boundary layer are computed from the SLP gradient and the crossisobar angle. 
* SLP is the sum of zonally averaged and azonal components. 
* The zonal component of SLP is derived based on the assumption that the strength and position of the major cells of the atmospheric meridional overturning circulation are controlled by average meridional temperature gradients and zonally averaged surface drag

* The zonally averaged SLP is directly related to the zonal mean meridional (ageostrophic) wind in
the planetary boundary layer and therefore the mean meridional circulation. 

* The vertical structure of the zonally averaged meridional circulation is parameterized

* The azonal component of mean SLP resulting from stationary planetary waves is separated into a thermal component and an orographic component. 

* The thermal component is assumed to be proportional to the azonal surface temperature anomaly reduced
to sea level using the interrelation between long-term largescale azonal temperature and pressure in quasi-stationary planetary-scale waves

* SESAM includes a prognostic equation for vertically integrated energy and another for total-column water content, from which surface air temperature and humidity are derived.

* Sources and sinks of energy in the column include net longwave and shortwave radiation, surface sensible heat flux and latent heat release from condensation. 

* Sources and sinks of water in the column are given by surface evaporation and precipitation. 

* The 3-D wind field is used to advect the 3-D potential temperature field and 3-D specific humidity fields.












